fabric8-analytics/fabric8-analytics-vscode-extension

package.json, src/extension.ts
- implements auth token in flow
=> implements auth token in flow

package.json, src/commands.ts, src/extension.ts, test/extension.test.ts, tsconfig.json
**adds integration test for extension**
- Extension should be present
- Should activate
- Should register all fabric8 commands
=> adds integration test for extension

src/extension.ts, src/stackanalysismodule.ts
- refactored stack analysis module
=> refactored stack analysis module

package.json, src/commands.ts, src/contentprovidermodule.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts
adds multi manifest support
- for maven, pypi, npm ecosystem
=> adds multi manifest support

src/apiendpoint.ts, src/contentprovidermodule.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, src/template.ts
- updates api endpoint into separate namespcae, code refactor
- code refactor
=> updates apiendpoint into separate namespcae, code refactor

src/multimanifestmodule.ts, test/extension.test.ts, tsconfig.json
=> updates test cases

package.json, src/apiendpoint.ts, src/authextension.ts, src/commands.ts, src/extension.ts, src/template.ts, test/extension.test.ts
=> adds handler for authorize and unauthorize f8-analytics

package.json, src/contentprovidermodule.ts, src/extension.ts
=> adds security to portal

package.json, src/authextension.ts, src/commands.ts, src/contentprovidermodule.ts, src/extension.ts, src/lspmodule.ts, test/extension.test.ts
fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/24
=> hand auth wrt to osio-auth extension

src/authextension.ts
=> test ci build

README.md, src/authextension.ts, src/extension.ts, src/stackanalysismodule.ts
=> adds proper storage variables for extension

package.json, src/authextension.ts
=> code refactor

package.json, src/contentprovidermodule.ts, src/stackanalysismodule.ts, src/template.ts
=> fixes unwanted popup

package.json, src/stackanalysismodule.ts, src/template.ts
fies https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/37, https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/36, https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/35
=> fixes issue with tip on loader screen, change command text

src/stackanalysismodule.ts
fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/21
=> fix single manifest file issue

src/apiendpoint.ts, src/authextension.ts, src/contentprovidermodule.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts
=> updates route

src/apiendpoint.ts
=> updates route for connect api

src/authextension.ts
=> updates service details

package.json, src/ProjectDataProvider.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, test/extension.test.ts
=> implements progress bar status, removes notification, extension pack

Jenkinsfile
=> updates lsp build in jenkins file

README.md, src/authextension.ts, src/contentprovidermodule.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, src/template.ts
=> minor corrections

src/apiendpoint.ts, src/authextension.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts
=> 3scale integration

fetch_lsp.sh
=> updates lsp release path

src/multimanifestmodule.ts, src/stackanalysismodule.ts, src/template.ts
=> updates endpoint name, handles custom msg for 403

README.md
=> updates readme with gif

src/authextension.ts
fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/85
=> fixes 401 issue with get-route

package.json, src/lspmodule.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts
=> fixes regex for filename issue

package.json
=> updates version of address not found issue

src/multimanifestmodule.ts
=> fixes lsp should ignore generated poms

README.md
Rewrote intro, updated language throughout.
=> updated language

package.json, src/multimanifestmodule.ts, src/stackanalysismodule.ts
=> pass license details as req payload for stack analysis

package.json
=> updates to package.json

package.json
Appearently we can only have 5.
=> fix the keyword limitation

LICENSE, package.json
=> updates license file

src/stackanalysismodule.ts
=> remove logs , update msg

src/multimanifestmodule.ts, src/stackanalysismodule.ts
=> updates text

package.json, src/ProjectDataProvider.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts
=> handles multiWS check, error handle in case of failure

src/stackanalysismodule.ts
=> adds log and update timeout

package.json, src/stackanalysismodule.ts
=> updates msg

src/ProjectDataProvider.ts, src/extension.ts, src/stackanalysismodule.ts
=> removes log

README.md, package.json, src/authextension.ts, src/contentprovidermodule.ts, src/extension.ts, src/stackanalysismodule.ts, src/template.ts, test/extension.test.ts
=> handles err for status code

src/extension.ts
=> removes unwanted notification

src/template.ts
=> adds styles

package.json, src/extension.ts
=> fixes issue with cmd to generate stack analysis on manifest file

README.md, package.json, src/multimanifestmodule.ts, src/stackanalysismodule.ts
=> adds log for 400

src/stackanalysismodule.ts
=> updates counter logic

src/apiendpoint.ts, src/authextension.ts
=> updates 3scale gateway routes

src/stackanalysismodule.ts
=> updates info msgs

src/contentprovidermodule.ts, src/extension.ts, src/stackanalysismodule.ts
=> updates context clear logic

.vscodeignore, package.json, src/ProjectDataProvider.ts, src/Utils.ts, src/apiendpoint.ts, src/contentprovidermodule.ts, src/extension.ts, src/lspmodule.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, tslint.json
=> fixes lint issues

src/ProjectDataProvider.ts, src/authextension.ts, src/contentprovidermodule.ts, src/extension.ts, src/lspmodule.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts
=> fixes tslint

package-lock.json, package.json, src/extension.ts, src/multimanifestmodule.ts, test/extension.test.ts, test/index.ts
fixes stack analyses issues with vscode 1.25
Tracks : https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/138
=> fix(stack-analysis): fixes stack analyses issues with vscode 1.25

src/ProjectDataProvider.ts, src/Utils.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts
1. Resolving Semantic version for stack analysis in the single manifest. 
2. Resolving Semantic version for stack analysis in the workspace level. 
3. Refactoring of code to accommodate node support.
4. Error handling
=> Feat node resolved dep manifest

README.md, package.json, src/Utils.ts
updates npm support in readme(s)
=> fix(readme): updates npm support in readme(s)

src/contentprovidermodule.ts
spelling mistake in the word analyze
=> spelling mistake in the word analyze

package.json
=> Fix languages

package.json, src/ProjectDataProvider.ts, test/extension.test.ts
Tracks : 
https://github.com/openshiftio/openshift.io/issues/4418
=> fix(npm-install): fixes issue with npm install on fresh repos

src/stackanalysismodule.ts
Passes null excludes to overwrite the default that
comes from user/workspace settings.
=> pass null excludes

test/extension.test.ts
=> fix(test): updates integration tests

package-lock.json, src/extension.ts
updates notification messages and info status
=> fix(info-icon): updates notification messages and info status

package-lock.json, package.json, src/commands.ts, src/extension.ts, src/statusMessages.ts
- feature to support quick fixes with code action
Tracks: 
https://github.com/openshiftio/openshift.io/issues/4516
=> fix(code-action): feature to support qucikfixes with codeaction

CHANGELOG.md, README.md, package-lock.json, package.json, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts
* fixes - minor bug fixes and updates READMEs, CHANGELOG
The screenshot was taken in IDE preview for READMEs
=> Fix readme changelog

.vscode/launch.json, README.md, package-lock.json, package.json, src/ProjectDataProvider.ts, src/Utils.ts, src/authextension.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackAnalysisService.ts, src/stackanalysismodule.ts, src/statusMessages.ts, test/extension.test.ts, test/multimanifestmodule.test.ts, test/projectDataProvider.test.ts, test/stackAnalysisService.test.ts, test/stackanalysismodule.test.ts, tslint.json
- python support for stack analyses on `requirements.txt`
- python support for component analyses on `requirements.txt`
- removes nested `callbacks` with `async await`
=> fix(pypi): python support for stack analyses

.vscode/settings.json, package.json, src/ProjectDataProvider.ts, src/multimanifestmodule.ts, src/stackAnalysisService.ts, src/stackanalysismodule.ts, src/template.ts, test/multimanifestmodule.test.ts, test/projectDataProvider.test.ts, test/stackanalysismodule.test.ts
- provides transitive support for maven ecosystem
- refactored stack analyses flow for a file and workspace
- removes license payload and extra findFiles
- includes path module
=> fix(transitive): provides transitive support for maven

package-lock.json, src/ProjectDataProvider.ts, src/multimanifestmodule.ts
use os module instead of process
=> fix(os) use os module instead of process

src/ProjectDataProvider.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts
- fixes issue with file explorer and removes mvn install
- removes mvn install
- Tracks  https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/279
=> fix(ext): fixes issue with fileexplorer and removes mvn install

package-lock.json, package.json, src/DepOutputChannel.ts, src/ProjectDataProvider.ts, src/Utils.ts, src/commands.ts, src/extension.ts, src/statusMessages.ts, test/DepOutputChannel.test.ts, test/authextension.test.ts, test/dependencyReportPanel.test.ts, test/extension.test.ts, test/multimanifestmodule.test.ts, test/stackAnalysisService.test.ts, test/stackanalysismodule.test.ts
Tracks: https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/281
=> fix(error): shows error in output channel

.vscodeignore, CHANGELOG.md, README.md, package-lock.json, package.json, src/ProjectDataProvider.ts, src/extension.ts
- updates Readmes and changelog for release
- fix progress issue with CHE
- adds show output channel button
- fixes issue with re run for npm app in win
=> fix(release): updates Readmes and changlog for release

src/ProjectDataProvider.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, test/multimanifestmodule.test.ts, test/projectDataProvider.test.ts, test/stackanalysismodule.test.ts
Tracks : 
1. https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/302
2. https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/299
=> Fix explorer workspace

.vscodeignore, CHANGELOG.md, package.json, src/stackAnalysisService.ts, src/stackanalysismodule.ts
Tracks : https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/304
=> fix(issues): fixes reg issues and updates changelog

src/extension.ts, src/multimanifestmodule.ts, test/extension.test.ts
Tracks: https://jira.coreos.com/browse/APPAI-368
=> fixes issue with running manifest file without having a workspace

package.json, src/ProjectDataProvider.ts, src/Utils.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, test/projectDataProvider.test.ts, test/utils.test.ts
=> feat(python): updates python support

package-lock.json, package.json
Use the following requirements.txt file to test, it has comments and spaces in between versions.
```
#####
connexion ==                       1.1.15          
flask ==                       0.12.2
spyder == 3.3.4
###
###
###
######
```
=> fix(lsp): Update fabric8-analytics-lsp-server to 0.1.56

Jenkinsfile
=> fix(vsix): Update extension publisher id

src/ProjectDataProvider.ts, src/statusMessages.ts
=> fix(pypi): Use pipe to run a pypi dependency collector script

src/ProjectDataProvider.ts
Fixes https://jira.coreos.com/browse/APPAI-1042
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
=> fix(pypi): Add quotes around file path to avoid space issues

package.json, src/authextension.ts, src/constants.ts, src/dependencyReportPanel.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, test/authextension.test.ts, test/dependencyReportPanel.test.ts, test/multimanifestmodule.test.ts
Changes related to v2 stack analysis
=> feat(v2): Integrate v2 CRDA API

src/apiendpoint.ts, src/authextension.ts, test/authextension.test.ts
chore: Update stage url of v2 Integration for Testing on stage
=> chore: [must be reverted] Update stage url of v2 integration for testing on stage

package-lock.json, package.json
chore: update Dependency Analytics Plugin version - 0.0.14-2020.06.25-1
=> chore: Change plugin version 0.0.14-2020-06-25-1

src/apiendpoint.ts, src/authextension.ts, test/authextension.test.ts
Reverts fabric8-analytics/fabric8-analytics-vscode-extension#382
=> Revert "chore: [must be reverted] Update stage url of v2 integration for testing on stage"

src/apiendpoint.ts
Stack-report-ui pointing to stage (must be reverted)
=> chore: [must be reverted] Use staging stack-report-ui for internal testing

package-lock.json, package.json
Upadate version to 0.0.14-rc-1 as a 1st release candidate
=> chore: Update version to 0.0.14-rc-1

CHANGELOG.md
Update CHANGELOG for release version 0.1.0
=> fix(changelog): Update CHANGELOG for release version 0.1.0

src/apiendpoint.ts
Reverts fabric8-analytics/fabric8-analytics-vscode-extension#391
=> Revert "chore: Use staging stack-report-ui for internal testing"

src/dependencyReportPanel.ts
Jira link: https://issues.redhat.com/browse/APPAI-1389
=> fix(issue): Add postMessage to handle url click in sa-ui

package-lock.json, package.json, src/authextension.ts, src/constants.ts, src/dependencyReportPanel.ts, src/stackanalysismodule.ts, test/authextension.test.ts
Get and store UUID in localStorage and use UUID in the api-calls via env. variable.
=> feat: Add anonymous user management/tracking 

src/authextension.ts
Log the error and move on if of getUUID() fails.
=> fix: log the error and move on if getUUID() fails

README.md, package.json, src/ProjectDataProvider.ts, src/Utils.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, test/projectDataProvider.test.ts
Added support for GO ecosystem:
https://issues.redhat.com/browse/APPAI-1462
=> feat: Golang Support for stack analyses

README.md, package.json, src/ProjectDataProvider.ts, src/Utils.ts, src/extension.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, test/projectDataProvider.test.ts
Reverts fabric8-analytics/fabric8-analytics-vscode-extension#407
=> Revert "feat: Golang Support for stack analyses"

src/apiendpoint.ts, src/authextension.ts, test/authextension.test.ts
Reverts fabric8-analytics/fabric8-analytics-vscode-extension#412
=> Revert "chore:  [Must be reverted] Update stage urls for user management testing on stage"

src/extension.ts
fix: Notification Button (Show Dependency Analytics Report by clicking on the notification button.)
=> fix: Notification Button

cico_setup.sh
Reverts fabric8-analytics/fabric8-analytics-vscode-extension#419
=> Revert "chore: Version pin vsce to 1.80.0"

Jenkinsfile
Add a Jenkins step to publish extension to Open VSX market place along with Microsoft VSCode market place.
=> feat: Publish to Open VSX Market place

package-lock.json, package.json, src/authextension.ts
- Upgrade to LSP 0.4.1 which supports fullstack report from codeactions
- Enable CodeActions through env variable PROVIDE_FULLSTACK_ACTION
Related: https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/149
=> fix: Use lsp 0.4.1 which supports fullstack report from codeactions

Jenkinsfile, vscode-yaml
Build fails on new PSI Jenkins infra without this update.
=> chore: Update build node & nodejs version used in deployment job

src/extension.ts
Change in message content for error case.
=> fix: [APPAI-1638] Remove `Powered By Snyk` from error popups

README.md
Adding **Common Errors and FAQ** to suggest easy and quick resolution.
=> chore: Update README.md for release version 0.3.0-beta

src/apiendpoint.ts, src/authextension.ts, test/authextension.test.ts
Reverts fabric8-analytics/fabric8-analytics-vscode-extension#444
=> Revert "chore: [Must be reverted] Update stage urls for Golang testing on stage"

package.json
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/442
=> fix: Remove shortcut-key bindings

package.json, test/runTest.ts
Jira Issue: https://issues.redhat.com/browse/APPAI-1680
=> fix: Update minimal required vscode version to 1.49.0

.github/workflows/main.yaml, package-lock.json, package.json
Update lsp to 0.4.20 which pickups fix for https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/178
Fixes https://issues.redhat.com/browse/APPAI-1710, https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/481
=> fix: Upgrade lsp to 0.4.20

package-lock.json, package.json, webpack.config.ts
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/493
=> fix: use lsp 0.4.24 to fix bug with empty manifests

.github/workflows/conventional-commit-msg.yml
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
=> chore: adopt conventional commits

src/ProjectDataProvider.ts
Simplified go manifest command executed during SA. Address issue raised by a user https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/504
=> fix: [APPAI-1819] Simplified go manifest generation command

README.md
=> chore: add dev-dependency disclaimer

README.md
Add documentation on how to use the Ignore Vulnerabilities feature.
=> docs: Add documentation on Ignore Vulnerabilities

package.json
Kindly asking for a review - I removed the "python"-language alias which causes #547
=> fix: jupyter-notebook issue issue-547

package.json
Tracks: https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/574
=> fix: remove language aliases

Jenkinsfile
This PR is to add my name to get access for releasing new extension version to Marketplace.
=> chore: Adding user name to get access for extension release in Marketplace.

README.md
Updates readme with information on GitHub Action. Also, some general clean-up, consistency and typos were fixed.
=> docs: Update README with CI information

package-lock.json, src/stackAnalysisService.ts, test/stackAnalysisService.test.ts
PR addresses an error occurring when requesting a dependency analysis report - status code 504 (which indicates that a server acting as a gateway was not able to get a response from the upstream server that it needs to complete the request).
In an effort to try and reduce the likeliness of this error occurring I have included an Exponential Backoff retry to the POST and GET services for stack analysis.
=> perf: retry stack analysis service

src/extension.ts
Added fileName as a key to segregate actions by language for reporting based on the file provided.
=> feat: Metrics Action Segregation

src/extension.ts
Added 'manifest' to go along with fileName as a key to segregate actions by language for reporting based on the file provided to match CLI.
=> feat: Added 'manifest' property to properties.

.github/workflows/stage.yml
=> ci: added stage workflow for creating early-access releases

.github/workflows/stage.yml
=> ci: fixed stage workflow

Jenkinsfile
=> chore: add tfigenbl as jenkins approver

CHANGELOG.md, package-lock.json, package.json
=> chore: prepare 0.3.7 release

Jenkinsfile
=> ci: jenking push to ovsx requires nodejs 14

CHANGELOG.md, package-lock.json, package.json
=> chore: prepare 0.3.8 release

CHANGELOG.md, package-lock.json, package.json
=> chore: prepare 0.3.9 release

.github/workflows/main.yaml, .github/workflows/stage.yml, Jenkinsfile, README.md
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/624
=> fix: Update version badge README.md

CHANGELOG.md, package-lock.json, package.json
=> chore: prepare 0.3.10 release

Jenkinsfile
=> ci: pinned jenkins vsce used to @vscode/vsce

Jenkinsfile
=> build: add zgrinber as jenkins release approver

Jenkinsfile
Ilona Will need to approve the release gate upon submission of the Jenkins job.
=> build: add ishishov as jenkins release approver

Jenkinsfile
add NPM_TOKEN secret to authenticate github package registry for pulling private packages
=> chore: add NPM_TOKEN secret to authenticate github package registry

Jenkinsfile
update to new Node tool ( version 18.16.1) in Jenkinsfile
=> chore: update to new Node tool ( version 18.16.1) in Jenkinsfile

README.md
Removed the important admonishment in the CI builds section of the README.md file.
=> docs: Removed GitHub action statement

package-lock.json, package.json, src/authextension.ts, src/dependencyReportPanel.ts, src/multimanifestmodule.ts, src/stackanalysismodule.ts, test/authextension.test.ts, test/dependencyReportPanel.test.ts, test/multiManifestModule.test.ts
1. Added MATCH_MANIFEST_VERSIONS to extension workspace settings and to Exhort JS API request
2. updgraded Exhort JS API version to 2.0.0-ea.39
3. Enhanced the dependencyReportPanel module
4. Updated unit tests
=> feat: added MATCH_MANIFEST_VERSIONS setting

package-lock.json, package.json, src/config.ts, test/config.test.ts
Added vulnerability alert severity setting which will allow the user to choose to receive inline dependency vulnerability alerts at Error or Warning level.
Solution to enhancement issue: #597
=> feat: add vulnerability alert severity setting

package-lock.json, package.json, src/caStatusBarProvider.ts, src/commands.ts, src/config.ts, src/constants.ts, src/exhortServices.ts, src/extension.ts, src/stackAnalysis.ts, src/tokenValidation.ts, test/caStatusBarProvider.test.ts, test/config.test.ts, test/dependencyReportPanel.test.ts, test/exhortServices.test.ts, test/extension.test.ts, test/stackAnalysis.test.ts, test/tokenValidation.test.ts
Migrated RHDA VSCode Extension to utilize the VSCode Secret Storage to enhance security by storing tokens in VSCode's built-in Secret Storage.
Renamed VSCode commands to align with the extension's naming convention.
=> chore: integrate secret storage

CHANGELOG.md, README.md
Removed any mention of Snyk in the README.md file, and added an entry into the CHANGELOG.md file.
=> docs: Removed mention of Snyk in documentation

CHANGELOG.md, README.md
Updates to the README.md and CHANGELOG.md files for an upcoming release.
=> docs: Updates to the README and CHANGELOG

CHANGELOG.md, README.md
Updated the CHANGELOG.md and README.md files with the new Docker scanning feature and settings.
=> docs: Updates to docs for Docker scanning

CHANGELOG.md, README.md
Reviewed known issue drafts. Added another known issue (TC-1558) to the `README.md` file.  Also updated the `CHANGELOG.md` file, plus a few minor edits for grammar.
=> docs: Added a KI to README, plus a few minor edits

.github/workflows/ci.yaml, package-lock.json, package.json, src/config.ts, src/stackAnalysis.ts
Fix #765 
Dependencies:
- https://github.com/trustification/exhort-javascript-api/pull/182
- https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/266
=> feat: add support for pnpm

package-lock.json, package.json, src/config.ts, src/stackAnalysis.ts, test/config.test.ts
Fix #712 
Depends on https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/270
=> feat: support configure a proxy url

package-lock.json, package.json, src/exhortServices.ts, test/exhortServices.test.ts, test/runTest.ts, transformToDynamicImport.sh, webpack.config.ts
=> fix: use of http proxy

package-lock.json, package.json
Incorporate https://github.com/trustification/exhort-javascript-api/pull/206
=> chore(deps): update js api to ea.74

package-lock.json, package.json
Bump dependencies to include latest changes
=> chore(deps): update js api to 0.2.1 and lsp 0.10.2

CHANGELOG.md
Replaces: https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/781
Fixes: Jira [TC-2493](https://issues.redhat.com/browse/TC-2493)
=> docs: add changelog for 0.9.6

package-lock.json, package.json
Upgrade to javascript api 0.2.3
=> chore: upgrade to js 0.2.3

package-lock.json, package.json, src/caStatusBarProvider.ts, src/dependencyAnalysis/analysis.ts, src/dependencyAnalysis/diagnostics.ts, src/diagnosticsPipeline.ts, src/exhortServices.ts, src/imageAnalysis.ts, src/imageAnalysis/analysis.ts, src/imageAnalysis/diagnostics.ts, src/providers/build.gradle.ts, src/providers/docker.ts, src/providers/go.mod.ts, src/providers/package.json.ts, src/providers/pom.xml.ts, src/providers/requirements.txt.ts, src/stackAnalysis.ts, src/template.ts, src/tokenValidation.ts, src/utils.ts, src/vulnerability.ts
Also fixes indentation to be 2 spaces across all files, there was some with 4 spaces. Review with whitespace changes hidden.
=> chore: bump javascript-api version

package-lock.json, package.json
build: updated package with v0.9.6
I realized that version is wrong when I generated a `.vsix` file for local installation.
=> build: updated package with v0.9.6
