package.json
src/ProjectDataProvider.ts
src/extension.ts
src/multimanifestmodule.ts

The support was inbuilt for the most part from a single manifests'
analysis perspective, however the option to do the same did not show up
in the context menu in the editor window.
The other change required was when running analysis on the complete
workspace it always looked for a pom.xml in the root and did not proceed
if one was not found, changed that to include both pom.xml and
package.json.
Signed-off-by: Avishkar Gupta <avgupta@redhat.com>

Changes to enable NPM support

---

src/ProjectDataProvider.ts

- checks if package.json has dependencies before accessing it
Tracks : 
https://github.com/openshiftio/openshift.io/issues/4337

fix(npm): checks if package.json has dependencies before accessing it

---

CHANGELOG.md
CONTRIBUTING.md
README.md
package-lock.json
package.json
src/commands.ts
src/extension.ts
src/multimanifestmodule.ts
src/stackanalysismodule.ts
src/statusMessages.ts
src/template.ts
test/extension.test.ts
test/stackanalysismodule.test.ts

Currently, there two separate commands to trigger stack analyses
- Generate Stack Analyses on Manifest
- Generate Stack Analyses on Workspace
With this change, user will have just one command
- View Dependency Analytics Report ... 
It'll handle both workspace and manifest flow depending on the context from it's being triggered.
- https://github.com/openshiftio/openshift.io/issues/4518

fix(command): updates two command to single to improve user experience

---

src/stackanalysismodule.ts

Currently transitive report is enabled only for PyPi, it should be enabled by default for other ecosystems(npm and maven) as well. We can back-out this changeset once it is enabled by default from platform.

fix(transitive): Enable transitive dependency report by default

---

src/ProjectDataProvider.ts

The main difference is `;` vs `&&`. Prior to this fix, `pylist.json` will be generated regardless of the outcome of `pip install -r requirments.txt`.
This fix mitigates generating incomplete stack report., and behaviour of pypi will match with the other ecosystems(maven & npm). 
Refer #327.

fix(pypi): Generate pylist.json only if pip install runs without error

---

src/constants.ts
src/extension.ts

Dependency Analytics version is retrieved from `package.json` and stored in `[globalState](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.globalState)`. Whenever a new version is updated and loaded into vscode, previous version will be retrieved from `globalState` and compared with current version to show the message.
This PR fixes #311.
Look at the notification from right bottom side of the below screenshot,

feat(welcome-msg): Show welcome message after upgrading to latest version

---

src/constants.ts
src/stackAnalysisService.ts
src/stackanalysismodule.ts

This PR fixes VSIX side of issue #304. Also it handles new HTTP error code which got introduced part of https://github.com/fabric8-analytics/fabric8-analytics-server/pull/576.
Polling duration is 20s, polling frequency 2s.

fix(timeout): Fix stack report polling frequency and duration

---

cico_setup.sh
test/runTest.ts

Current npm which comes part of node 6.x doesn't honours `package-lock.json`. Also node 6.x is pretty old and no longer supported.

fix(node): Upgrade node version to 14.x LTS

---

package-lock.json
package.json

- https://www.npmjs.com/package/fabric8-analytics-lsp-server

chore: Update to latest fabric8-analytics-lsp-server to 0.2.1

---

package-lock.json
package.json

Update to latest fabric8-analytics-lsp-server to 0.2.2

chore: Update fabric8-analytics-lsp-server version to 0.2.2

---

package-lock.json
package.json

https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/releases/tag/v0.2.8 
https://www.npmjs.com/package/fabric8-analytics-lsp-server/v/0.2.8

chore: Update fabric8-analytics-lsp-server version to 0.2.8

---

src/extension.ts

Rename notification button with `'Click here for Detailed Vulnerability Report'`

fix: Rename notification button with 'Click here for Detailed Vulnerability Report'

---

src/extension.ts

As part of Golang CA implementation on LSP, we need an option to notify LSP client about parsing / manifest file errors. This PR is to support such generic error propagation from LSP server to LSP client.
Jira TIcket :: https://issues.redhat.com/browse/APPAI-1524

fix: Propagate errors from lsp server to client

---

src/authextension.ts

Need to propagate go executable (binary) path to LSP server in order to trigger golang CA.
fixes jira ticket :: https://issues.redhat.com/browse/APPAI-1636

fix: [APPAI-1636] Propagating go binary path to LSP

---

Jenkinsfile

Use the umbrella vscode directory similar to other RedHat VSCode extensions.
Example: https://github.com/redhat-developer/vscode-openshift-extension-pack/blob/master/openshift-java/Jenkinsfile
New location weblink: https://download.jboss.org/jbosstools/vscode/stable/

chore: Change UPLOAD_LOCATION to align with other RH extensions

---

src/ProjectDataProvider.ts

SA report adds build manifest package as dependency in go.mod. Runing build manifest command on non-project root folder avoid go.mod update.
Jira ticket :: https://issues.redhat.com/browse/APPAI-1643

fix: [APPAI-1643][Golang][LSP][VS Code] SA report adds build manifest package as dependency in go.mod

---

src/ProjectDataProvider.ts

Modified go manifest generation command to avoid usage of 'cd' which was giving problem on some systems. Also now command gets gomanifest package first and then runs it. This also avoids updating go.mod file.
Jira ticket :: https://issues.redhat.com/browse/APPAI-1650

fix: [APPAI-1650][Golang] SA gives error on few operating system

---

src/caNotification.ts
src/caStatusBarProvider.ts
src/extension.ts
src/statusMessages.ts

Singular/plural cases are handled:
No vulnerabilities case:
Changes are made based on the discussion with @fbricon.
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/434

fix: Update status bar to have concise text

---

src/caNotification.ts
src/caStatusBarProvider.ts
src/extension.ts
src/statusMessages.ts

- Update popup to show concise text (in sync with status bar text)
- Fix popup full stack report label to be consistent with status tool tip
- Don’t silence error popup
Also fixes https://issues.redhat.com/browse/APPAI-1679

fix: Use concise text for CA popup

---

Jenkinsfile

Publish to VSCode market place has been temporarily disabled to passthrough OVSX publish step.

chore: Fix OVSX publish failure

---

src/caStatusBarProvider.ts
src/extension.ts

Associate status bar command with manifest file which generated the current status text.
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/478

fix: Bind status bar text with respective manifest path

---

src/ProjectDataProvider.ts
src/config.ts
src/msPythonExtension.ts
test/config.test.ts
test/projectDataProvider.test.ts

Prior to this PR, we were relying only on `python.pythonPath` which is
extremely hard to maintain if user switches between multiple projects with
different python versions. Also our extension doesn't automatically
finds venv.
ms-python[1] extension scans entire workspace and discovers virtual env. It
also provides nice interface to select and switch between various venvs.
This PR makes use of the APIs[2] exposed by ms-python to fetch the
selected interpreter path.
Extension fallbacks to default behaviour incase if there is no ms-python
installed.
This also should work seamlessly when user has multi-root vscode workspaces[3].
TODO: Recommend users to install ms-python if it is not
already installed.
[1] https://marketplace.visualstudio.com/items?itemName=ms-python.python
[2] …

feat: Get python path from ms-python extension

---

src/ProjectDataProvider.ts
src/stackanalysismodule.ts
test/projectDataProvider.test.ts

Stack analyses does not get trigger for windows for golang. The issue was with folder path passed to the `gomanifest` binary to generate `golist.json`. The last '\' amd '/' in path caused command line parameter to be passed wrongly. 
Fixes user issue https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/506
Jira ticket :: https://issues.redhat.com/browse/APPAI-1838
Changes were tested on Linux, WIndows and Mac with go1.16 and go1.14

fix: [APPAI-1838] [Golang] SA does not trigger on windows

---

package-lock.json
package.json
src/caNotification.ts
src/extension.ts

if `cacheMissCount > 0` evaluates to true then there was a api call from lsp to the backend. Record this as 
`component_analysis_done` event.
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>

fix: send component_analysis_done only if api call is made

---

package.json
src/commands.ts
test/extension.test.ts
test/resources/sampleNodeApp/package.json

fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/512

fix: hide internal analytics commands from command palette

---

src/ProjectDataProvider.ts

fix dependency analysis report for Golang manifest,
using `go get` to install modules as executables was deprecated in go 1.17, `go install` should be used instead.
reference: https://go.dev/doc/go-get-install-deprecation

fix: vscode plugin

---

Jenkinsfile

ci: jenkins should run on node 12 to avoid dependency versions errors

---

CHANGELOG.md
src/config.ts
src/constants.ts

Resolve endpoint configuration issue by removing EXHORT_DEV_MODE environment configuration parameter.

fix: endpoint configuration issue

---

CHANGELOG.md
README.md

I've updated the `CHANGELOG.md` and `README.md` files for the upcoming patch release.

docs: Updates to the change log and readme files for upcoming patch release

---

README.md

The ONGuard content has been removed, because it's only a back-end service, not IDE specific.

docs: Removed the ONGuard content

---

CHANGELOG.md
README.md

Updates to the `README.md` and `CHANGELOG.md` files for the additional support for Gradle build manifests.

docs: Updates to the readme and changelog for Gradle feature

---

CONTRIBUTING.md
README.md

Added `exhortignore` content for Gradle to the `README.md` file, and updated the `CONTRIBUTING.md` file as to reflect the current project policy. Also includes a few other minor edits to the content.

docs: Updated the README and CONTRIBUTING docs

---

.vscode/tasks.json
package-lock.json
package.json
src/config.ts
src/exhortServices.ts
src/extension.ts
src/imageAnalysis.ts
src/redhatTelemetry.ts
src/rhda.ts
src/stackAnalysis.ts
src/template.ts
test/rhda.test.ts

Removes extraneous `try { } catch(e) { throw e }`, unwraps usage of `new Promise` wrapped by try catch into direct async-awaits, and some other minor formatting changes/multiline string usage/missing parameter types.

chore: refactor usage of promises into async/await

---

src/extension.ts

File diagnostics for package.json won't be triggered if the user has package.json files associated with `jsonc` language ID instead of `json`. Fixed by having the LSP also receive events for jsonc files
Fix #760

fix: add JSONC listening for when package.json has jsonc file association

---

src/depOutputChannel.ts
src/extension.ts
src/imageAnalysis.ts
src/rhda.ts
src/stackAnalysis.ts
src/utils.ts
test/depOutputChannel.test.ts
test/imageAnalysis.test.ts
test/rhda.test.ts
test/stackAnalysis.test.ts
tsconfig.json

Instead of having a completely empty log section, time to actually put something semi-useful for the "Red Hat Dependency Analytics: Debug logs" command :smile:

feat: include logging the invoking & erroring of generating RHDA reports

---

.github/workflows/stage.yml

We were building the vsix and only _later_ bumping the version, so package.json in the vsix contained version X.Y.Z-1 but the code for X.Y.Z

fix: released package.json version was version behind

---

.eslintrc.js
src/caNotification.ts
src/dependencyAnalysis/diagnostics.ts
src/extension.ts
src/fileHandler.ts
src/imageAnalysis.ts
src/imageAnalysis/diagnostics.ts
src/stackAnalysis.ts
src/utils.ts
test/caNotification.test.ts

Changes made:
1. Vulnerabilities-found notification includes the manifest filepath 
2. Stack analysis report errors follow the same change as in https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/799
3. Customized the logs shown in notification popup vs in logs. Notifications include less details and for certain errors with extra output (such as command errors with stdout/stderr) we direct users towards the logs Output panel

feat: improve UX for error messages in logs & notifications

---

src/extension.ts

feat: add metric names to LLM model cards hover and only include basics

---

README.md

Update code language syntax for `gradle` because the right language is `groovy`
Fix https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/815

docs: update markdown syntax for gradle-groovy

---

README.md

Related to #814 
It seems there are some indentation problems that are only visible in the Extension documentation

docs: align code block formatting in README.md

---

src/extension.ts
src/redhatTelemetry.ts

1.
LLM models referenced in `@rhda` annotations that are known on the backend.
Key: `llm_analysis_model_annotations_discovered`
Values: a sorted array of model names
Frequency: whenever a file contains the `@rhda` annotation with a set of models differing to the previous set of models associated with the file is opened or updated
2.
LLM diagnostic/squiggle is hovered over.
Key: `llm_analysis_diagnostics_hovered`
Values: `modelName`: the model name
Frequency: whenever code actions are generated, which should happen when hovering over the generated diagnostics/squiggle. This may be cached by the editor, but at a minimum should happen at least once per code range
3.
LLM analysis report is generated
Key: `llm_analysis_report_done`
Values: `modelName`: the model name
Frequency: whenever the …

feat: add telemetry for LLM models referenced in annotations, hovered on and reports generated for

---

src/extension.ts

Reverts fabric8-analytics/fabric8-analytics-vscode-extension#811 due to misunderstanding what "visible" means resulting in component analysis not being triggered when we want it to be

fix: revert "don't run component analysis for files opened not by the user"

---

.github/workflows/stage.yml
package-lock.json
package.json

All staged versions assume the next version is a patch release e.g. if the latest release is 0.10.0 then staged artifacts will be 0.10.1-ea.<revhash>.

chore(ci): use current released version in package.json and bump to next patch in stage

---

.github/workflows/release.yaml

Closes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/839
`package.json` contains `0.10.1`, but the version we previously used was the output from `npm version` which already includes the `v` prefix. Hence we have to manually add the prefix now

fix: prefix release/tag with v
